title: The Debt Collective
author: The Debt Collective
email: organizers@debtcollective.org
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
rss: rss

theme: jekyll-debtcollective

plugins:
  # - jekyll-feed
  # - jekyll-seo-tag

collections:
  posts:
    output: true
  news_analysis:
    output: true
    permalink: /news-analysis/:name
  profiles:
    output: true
    permalink: /profiles/:title
  pages:
    output: true
    permalink: /:name